# Configuration for the MH-Z19B CO₂ sensor
#
# Used substitutions:
#
# - mhz19b_pin_tx: pin connected to the TX pin of the sensor
# - mhz19b_pin_rx: pin connected to the RX pin of the sensor
# - mhz19b_update_interval: update interval of the sensor
# - mhz19b_calibration_interval: calibration interval of the sensor
# - node_name: name of the device
#
# IDs used outside this file:
#
# - co2_value: the CO₂ concentration measured by the sensor
# - co2_calibrated: the calibration state of the sensor

uart:
  - id: uart_mhz19b
    rx_pin: ${mhz19b_pin_tx}
    tx_pin: ${mhz19b_pin_rx}
    baud_rate: 9600

sensor:
  - platform: mhz19
    id: co2_sensor
    uart_id: uart_mhz19b
    co2:
      name: "${node_name} CO₂"
      id: co2_value
      on_value:
        then:
          - script.execute: update_aqi
    update_interval: ${mhz19b_update_interval}
    automatic_baseline_calibration: false

# Show the user whether the sensor has been calibrated yet
binary_sensor:
  - platform: template
    name: "${node_name} CO₂ sensor calibrated"
    id: co2_calibrated
    on_press:
      then:
        - switch.turn_on: show_calibrating
    on_release:
      then:
        - switch.turn_off: show_calibrating

# The sensor starts in an uncalibrated state after boot
esphome:
  on_boot:
    priority: 500
    then:
      - binary_sensor.template.publish:
          id: co2_calibrated
          state: OFF

# Warn when the calibration interval has passed.
interval:
  - interval: ${mhz19b_calibration_interval}
    then:
      - binary_sensor.template.publish:
          id: co2_calibrated
          state: OFF

# Switch to calibrate the sensor from within Home Assistant.
switch:
  - platform: template
    name: "${node_name} calibrate CO₂ sensor"
    id: co2_calibrate
    optimistic: true
    on_turn_on:
      then:
        - mhz19.calibrate_zero: co2_sensor
        - switch.turn_on: show_calibrating
        - delay: 20min
        - switch.turn_off: co2_calibrate
        - binary_sensor.template.publish:
            id: co2_calibrated
            state: ON
